spring.application.name=SoftDevoluciones
server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/Soft_Devoluciones_DB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto explícito para PostgreSQL (Recomendado)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Clave secreta para firmar JWT
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVDEyMzQ1Njc4OTA=
# Tiempo de expiración en milisegundos
jwt.expiration=86400000
#jwt = 24 horas = 86400000
#jwt 5 minutes = 300000